### ISSUE TITLE
Convert action to dotnet

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/TagVerifier#10]
### I have done the items below . . .

- [X] I have created a title but left the 🚧 emoji behind.

### Description

Convert this GitHub action from typescript/javascript style to C# style project.  To help speed things up, rename this project by prefixing the end with OLD,  then create a new project using the new [DotNetGitHubActionTemplate](https://github.com/KinsonDigital/DotNetGitHubActionTemplate) template repo.

Then use the old code base as a guide to help rebuild this new action.

⚠️Once the new project creation is complete, transfer this issue to the new project!!⚠️

### Acceptance Criteria

**This issue is finished when:**
- [ ] Action converted
- [ ] Unit tests created
- [ ] All unit tests pass
- [ ] Project repo setup for contributions and `FUNDING.yml` added to project
- [ ] Add badges to the README file
- [ ] Make sure to use the new **KDAdminUtils** library project for all of the shared action boilerplate code that is used across the organization

### ToDo Items

- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked  to the project milestone

### Issue Dependencies

- KinsonDigital/issues-repo#28
