### ISSUE TITLE
🚧Remove Code of Conduct 

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/TagVerifier#11]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove code of conduct file from the root of the repository so that it can use the org level document. 

### Acceptance Criteria

**This issue is finished when:**
- [x] Code of Conduct file removed

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
